/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppRapidRouteImport } from './routes/_app/rapid'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPatientIdWorkspaceRouteImport } from './routes/_app/patient.$id.workspace'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppRapidRoute = AppRapidRouteImport.update({
  id: '/rapid',
  path: '/rapid',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientIdWorkspaceRoute = AppPatientIdWorkspaceRouteImport.update({
  id: '/patient/$id/workspace',
  path: '/patient/$id/workspace',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/rapid': typeof AppRapidRoute
  '/register': typeof AppRegisterRoute
  '/patient/$id/workspace': typeof AppPatientIdWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/rapid': typeof AppRapidRoute
  '/register': typeof AppRegisterRoute
  '/patient/$id/workspace': typeof AppPatientIdWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/rapid': typeof AppRapidRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/patient/$id/workspace': typeof AppPatientIdWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/rapid'
    | '/register'
    | '/patient/$id/workspace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/rapid' | '/register' | '/patient/$id/workspace'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/rapid'
    | '/_app/register'
    | '/_app/patient/$id/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rapid': {
      id: '/_app/rapid'
      path: '/rapid'
      fullPath: '/rapid'
      preLoaderRoute: typeof AppRapidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient/$id/workspace': {
      id: '/_app/patient/$id/workspace'
      path: '/patient/$id/workspace'
      fullPath: '/patient/$id/workspace'
      preLoaderRoute: typeof AppPatientIdWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppRapidRoute: typeof AppRapidRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppPatientIdWorkspaceRoute: typeof AppPatientIdWorkspaceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppRapidRoute: AppRapidRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppPatientIdWorkspaceRoute: AppPatientIdWorkspaceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
