/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppRapidRouteImport } from './routes/_app/rapid'
import { Route as AppPatientsRouteImport } from './routes/_app/patients'
import { Route as AppMedicationsRouteImport } from './routes/_app/medications'
import { Route as AppLabsRouteImport } from './routes/_app/labs'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnalyticsV3RouteImport } from './routes/_app/analytics-v3'
import { Route as AppMastersMedicationsRouteImport } from './routes/_app/masters.medications'
import { Route as AppMastersLabPanelsRouteImport } from './routes/_app/masters.lab-panels'
import { Route as AppPatientIdWorkspaceRouteImport } from './routes/_app/patient.$id.workspace'
import { Route as AppPatientIdDashboardRouteImport } from './routes/_app/patient.$id.dashboard'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppRapidRoute = AppRapidRouteImport.update({
  id: '/rapid',
  path: '/rapid',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicationsRoute = AppMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => AppRoute,
} as any)
const AppLabsRoute = AppLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsV3Route = AppAnalyticsV3RouteImport.update({
  id: '/analytics-v3',
  path: '/analytics-v3',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersMedicationsRoute = AppMastersMedicationsRouteImport.update({
  id: '/masters/medications',
  path: '/masters/medications',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersLabPanelsRoute = AppMastersLabPanelsRouteImport.update({
  id: '/masters/lab-panels',
  path: '/masters/lab-panels',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientIdWorkspaceRoute = AppPatientIdWorkspaceRouteImport.update({
  id: '/patient/$id/workspace',
  path: '/patient/$id/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientIdDashboardRoute = AppPatientIdDashboardRouteImport.update({
  id: '/patient/$id/dashboard',
  path: '/patient/$id/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics-v3': typeof AppAnalyticsV3Route
  '/dashboard': typeof AppDashboardRoute
  '/labs': typeof AppLabsRoute
  '/medications': typeof AppMedicationsRoute
  '/patients': typeof AppPatientsRoute
  '/rapid': typeof AppRapidRoute
  '/register': typeof AppRegisterRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/masters/lab-panels': typeof AppMastersLabPanelsRoute
  '/masters/medications': typeof AppMastersMedicationsRoute
  '/patient/$id/dashboard': typeof AppPatientIdDashboardRoute
  '/patient/$id/workspace': typeof AppPatientIdWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics-v3': typeof AppAnalyticsV3Route
  '/dashboard': typeof AppDashboardRoute
  '/labs': typeof AppLabsRoute
  '/medications': typeof AppMedicationsRoute
  '/patients': typeof AppPatientsRoute
  '/rapid': typeof AppRapidRoute
  '/register': typeof AppRegisterRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/masters/lab-panels': typeof AppMastersLabPanelsRoute
  '/masters/medications': typeof AppMastersMedicationsRoute
  '/patient/$id/dashboard': typeof AppPatientIdDashboardRoute
  '/patient/$id/workspace': typeof AppPatientIdWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics-v3': typeof AppAnalyticsV3Route
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/labs': typeof AppLabsRoute
  '/_app/medications': typeof AppMedicationsRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/rapid': typeof AppRapidRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/masters/lab-panels': typeof AppMastersLabPanelsRoute
  '/_app/masters/medications': typeof AppMastersMedicationsRoute
  '/_app/patient/$id/dashboard': typeof AppPatientIdDashboardRoute
  '/_app/patient/$id/workspace': typeof AppPatientIdWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics-v3'
    | '/dashboard'
    | '/labs'
    | '/medications'
    | '/patients'
    | '/rapid'
    | '/register'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/masters/lab-panels'
    | '/masters/medications'
    | '/patient/$id/dashboard'
    | '/patient/$id/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics-v3'
    | '/dashboard'
    | '/labs'
    | '/medications'
    | '/patients'
    | '/rapid'
    | '/register'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/masters/lab-panels'
    | '/masters/medications'
    | '/patient/$id/dashboard'
    | '/patient/$id/workspace'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/analytics-v3'
    | '/_app/dashboard'
    | '/_app/labs'
    | '/_app/medications'
    | '/_app/patients'
    | '/_app/rapid'
    | '/_app/register'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/masters/lab-panels'
    | '/_app/masters/medications'
    | '/_app/patient/$id/dashboard'
    | '/_app/patient/$id/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rapid': {
      id: '/_app/rapid'
      path: '/rapid'
      fullPath: '/rapid'
      preLoaderRoute: typeof AppRapidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medications': {
      id: '/_app/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AppMedicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labs': {
      id: '/_app/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof AppLabsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics-v3': {
      id: '/_app/analytics-v3'
      path: '/analytics-v3'
      fullPath: '/analytics-v3'
      preLoaderRoute: typeof AppAnalyticsV3RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/medications': {
      id: '/_app/masters/medications'
      path: '/masters/medications'
      fullPath: '/masters/medications'
      preLoaderRoute: typeof AppMastersMedicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/lab-panels': {
      id: '/_app/masters/lab-panels'
      path: '/masters/lab-panels'
      fullPath: '/masters/lab-panels'
      preLoaderRoute: typeof AppMastersLabPanelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient/$id/workspace': {
      id: '/_app/patient/$id/workspace'
      path: '/patient/$id/workspace'
      fullPath: '/patient/$id/workspace'
      preLoaderRoute: typeof AppPatientIdWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient/$id/dashboard': {
      id: '/_app/patient/$id/dashboard'
      path: '/patient/$id/dashboard'
      fullPath: '/patient/$id/dashboard'
      preLoaderRoute: typeof AppPatientIdDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsV3Route: typeof AppAnalyticsV3Route
  AppDashboardRoute: typeof AppDashboardRoute
  AppLabsRoute: typeof AppLabsRoute
  AppMedicationsRoute: typeof AppMedicationsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppRapidRoute: typeof AppRapidRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppMastersLabPanelsRoute: typeof AppMastersLabPanelsRoute
  AppMastersMedicationsRoute: typeof AppMastersMedicationsRoute
  AppPatientIdDashboardRoute: typeof AppPatientIdDashboardRoute
  AppPatientIdWorkspaceRoute: typeof AppPatientIdWorkspaceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsV3Route: AppAnalyticsV3Route,
  AppDashboardRoute: AppDashboardRoute,
  AppLabsRoute: AppLabsRoute,
  AppMedicationsRoute: AppMedicationsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppRapidRoute: AppRapidRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppMastersLabPanelsRoute: AppMastersLabPanelsRoute,
  AppMastersMedicationsRoute: AppMastersMedicationsRoute,
  AppPatientIdDashboardRoute: AppPatientIdDashboardRoute,
  AppPatientIdWorkspaceRoute: AppPatientIdWorkspaceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
